<?php

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class TicTacToe {
	private $tic_tac_toe_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'tic_tac_toe_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'tic_tac_toe_page_init' ) );
	}

	public function tic_tac_toe_add_plugin_page() {
		add_options_page(
			'Tic-Tac-Toe', // page_title
			'Tic-Tac-Toe', // menu_title
			'manage_options', // capability
			'tic-tac-toe', // menu_slug
			array( $this, 'tic_tac_toe_create_admin_page' ) // function
		);
	}

	public function tic_tac_toe_create_admin_page() {
		$this->tic_tac_toe_options = get_option( 'tic_tac_toe_option_name' ); ?>

		<div class="wrap">
			<h2>Tic-Tac-Toe</h2>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'tic_tac_toe_option_group' );
					do_settings_sections( 'tic-tac-toe-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function tic_tac_toe_page_init() {
		register_setting(
			'tic_tac_toe_option_group', // option_group
			'tic_tac_toe_option_name', // option_name
			array( $this, 'tic_tac_toe_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'tic_tac_toe_setting_section', // id
			'Configuration', // title
			array( $this, 'tic_tac_toe_section_info' ), // callback
			'tic-tac-toe-admin' // page
		);

		add_settings_field(
			'premier_joueur_0', // id
			'Premier joueur', // title
			array( $this, 'premier_joueur_0_callback' ), // callback
			'tic-tac-toe-admin', // page
			'tic_tac_toe_setting_section' // section
		);
	}

	public function tic_tac_toe_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['premier_joueur_0'] ) ) {
			$sanitary_values['premier_joueur_0'] = $input['premier_joueur_0'];
		}

		return $sanitary_values;
	}

	public function tic_tac_toe_section_info() {

	}

	public function premier_joueur_0_callback() {
		?> <select name="tic_tac_toe_option_name[premier_joueur_0]" id="premier_joueur_0">
			<?php $selected = (isset( $this->tic_tac_toe_options['premier_joueur_0'] ) && $this->tic_tac_toe_options['premier_joueur_0'] === 'host') ? 'selected' : '' ; ?>
			<option value="host" <?php echo $selected; ?>>Hote</option>
			<?php $selected = (isset( $this->tic_tac_toe_options['premier_joueur_0'] ) && $this->tic_tac_toe_options['premier_joueur_0'] === 'guest') ? 'selected' : '' ; ?>
			<option value="guest" <?php echo $selected; ?>>Invite</option>
			<?php $selected = (isset( $this->tic_tac_toe_options['premier_joueur_0'] ) && $this->tic_tac_toe_options['premier_joueur_0'] === 'winner') ? 'selected' : '' ; ?>
			<option value="winner" <?php echo $selected; ?>>Dernier gagnant</option>
			<?php $selected = (isset( $this->tic_tac_toe_options['premier_joueur_0'] ) && $this->tic_tac_toe_options['premier_joueur_0'] === 'loser') ? 'selected' : '' ; ?>
			<option value="loser" <?php echo $selected; ?>>Dernier perdant</option>
		</select> <?php
	}

}
if ( is_admin() )
	$tic_tac_toe = new TicTacToe();

/*
 * Retrieve this value with:
 * $tic_tac_toe_options = get_option( 'tic_tac_toe_option_name' ); // Array of All Options
 * $premier_joueur_0 = $tic_tac_toe_options['premier_joueur_0']; // Premier joueur
 */